### ISSUE TITLE
iamport-andorid 라이브러리에대한 질문

### ISSUE THREAD

**Issue by YKW93** [iamport/iamport-android#19]
안녕하세요 iamport 에 적용에 대해 몇가지 궁금한 점이 생겨 질문을 남기게 되었습니다.

1.  현재 버전이 0.0.5 버전인데 실제 앱에서 해당 라이브러리를 사용해도 괜찮을까요?
2. 내부 sdk에 있는 webviewactivity 디자인을 커스텀 할 방법이 혹시 따로 있을까요?

감사합니다.

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다.

1. 사용 가능합니다.
2. 현재는 지원 예정이 없습니다만, 어떤 디자인 커스텀을 말씀하시는지요?

감사합니다.

**Comment by YKW93** [comment]
> 안녕하세요. 아임포트 기술지원팀입니다.
> 
> 
> 
> 1. 사용 가능합니다.
> 
> 2. 현재는 지원 예정이 없습니다만, 어떤 디자인 커스텀을 말씀하시는지요?
> 
> 
> 
> 감사합니다.

답변 감사합니다! 디자인은 커스텀이라기 보다는 그 웹뷰 액티비티의 xml에서 툴바를 추가하고싶어서 질문을 드리게되었습니다

**Comment by kjh5833** [comment]
대부분의 결제창이 보통 하나의 PG 사 UI 로 구성되어 있기도 하고, 여러 이유로 지원하지 않는데요.

같은 의견을 주시는 분이 많다면 긍정적인 검토를 할 수 있을 것 같습니다.

현시점에서 굳이 쓴다고 하시면 fork 하셔서 사용하셔야 할 것 같습니다.

의견 감사드립니다!

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다.

**_v1.0.0-dev03_** 부터 webview mode 를 지원합니다.

원하시는 환경으로 Activity or Fragment 를 구성하시고,
Iamport.payment 호출 전,
Iamport.enableWebViewMode(webview) 으로 넘겨주시면 됩니다.

기회가 되시면 한번 사용해보시고, 피드백 주시면 서비스 개선에 도움이 될 것 같습니다.

https://github.com/iamport/iamport-android/releases/tag/v1.0.0-dev03
감사합니다.

**Comment by YKW93** [comment]
> 안녕하세요. 아임포트 기술지원팀입니다.
> 
> **_v1.0.0-dev03_** 부터 webview mode 를 지원합니다.
> 
> 원하시는 환경으로 Activity or Fragment 를 구성하시고,
> Iamport.payment 호출 전,
> Iamport.enableWebViewMode(webview) 으로 넘겨주시면 됩니다.
> 
> 기회가 되시면 한번 사용해보시고, 피드백 주시면 서비스 개선에 도움이 될 것 같습니다.
> 
> https://github.com/iamport/iamport-android/releases/tag/v1.0.0-dev03
> 감사합니다.

Fork 떠서 사용하고 있었는데 이렇게 기능 지원해주셔서 감사합니다!!
