### ISSUE TITLE
v0.0.5 버전에 대한 질문

### ISSUE THREAD

**Issue by YKW93** [iamport/iamport-android#24]
안녕하세요 현재 v0.0.5 버전을 fork 해서 사용중입니다.

앱을 release모드로 실행해도 chuck가 실행되는데.. 실행을 되지 않게 막을수 있는 방법이 있을까요?

감사합니다.

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다.

해당 chuck 문제가 있어 삭제하였으며,
최신버전인 v0.0.6-dev15 버전으로 사용해보시기 바랍니다.

감사합니다.

**Comment by YKW93** [comment]
빠른 답변 감사합니다 확인했습니다!

추가적으로 문의 사항이 있습니다.

현재 현대 카드 -> 일반 결제 선택 후 "설치하기", "결제하기" 클릭 시 결제 웹뷰가 꺼지는 현상이 있습니다.

참고로 결제에 필요한 백신 설치는 완료된 상태이며 pg사 는 이니시스 입니다. (해당 프로젝트 샘플앱도 동일한 현상 발생)
(에러 내용 : code -6, description net::ERR_CONNECTION_REFUSED)

감사합니다.

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술 지원팀입니다.
사용에 불편을 드려 죄송합니다.

내부적으로 onReceivedError 때의 처리를 위해
방어코드로 종료를 시키는 부분이 있는데,
웹뷰 자체에서 load 에 문제가 없어도 해당 메소드가 불리는 듯 합니다.

이는 chrome inspect 로 디버깅을 시도할 때도 발생하여 인지하고 있었던 이슈이나 
결제에는 문제가 없어서 따로 처리하지 않았습니다만

보내주신 이슈처럼 실제 결제에도 문제가 생긴다고 판단하여 
코드를 수정하고 v0.0.6-dev16 으로 배포를 하였습니다. 

최신 버전으로 사용해보시기 바라며 이슈 리포팅에 감사드립니다.
감사합니다.

**Comment by YKW93** [comment]
빠른 대응 감사합니다! 

확인 해보니 문제없이 잘 작동하는거 같습니다.

감사합니다.
