### ISSUE TITLE
SDK 26 대응 관련

### ISSUE THREAD

**Issue by dev-juyoung** [iamport/iamport-android#26]
안녕하세요. 해당 라이브러리를 이용하여 결제 모듈을 연동했습니다.
연동 진행 중 아래와 같은 이슈가 있어 공유드리며 해결 가능한 버전에 대해서 문의드립니다.

v0.0.5에서 Koin을 사용하는 Application에서 ViewModel 의존성 주입과 관련한 이슈가 있습니다.
해당 이슈는 v0.0.6-dev31 버전으로 라이브러리 버전 변경 시 해결된 것으로 보이나 Pre release 버전이라 사용하기에 조심스럽습니다. v0.0.6의 정식 release 계획은 언제인지 알 수 있을까요?

추가로 SDK 26을 사용하는 기기에서 `Only fullscreen opaque activities can request orientation` 이슈가 발생하는 것으로 보입니다.
해당 이슈가 해결 가능한지, 가능하다면 언제 release 되는지 궁금합니다.

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다. 
큰 문제가 없다면 금주 내에 v0.0.6 릴리즈 예정입니다.
SDK 26 호환 이슈까지 수정해서 릴리즈 하도록 하겠습니다. 
관심 가져주셔서 감사합니다.

**Comment by kjh5833** [comment]
v0.0.6-dev32 릴리즈에 SDK 26 에러를 수정하였습니다. 
확인 부탁드립니다.

**Comment by dev-juyoung** [comment]
안녕하세요. SDK 26에서 정상 동작하는 것 확인했습니다.
빠른 대응 감사합니다.

**Comment by kjh5833** [comment]
v0.0.6 배포되었습니다. 감사합니다!
