### ISSUE TITLE
정기결제를 붙이고 싶은데 IamPortRequest에 customer_uid 의 변수가 없네요

### ISSUE THREAD

**Issue by hanbit-valla** [iamport/iamport-android#28]
빌링키를 발급받으려면 customer_uid 가 필수인데, 혹시 추가될 예정인가요?
아니면 다른 방법이 있는지 궁금합니다

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다.
[IamPortRequest class 에서 customer_uid 파라미터를 제공하고 있습니다.](https://github.com/iamport/iamport-android/blob/a8e5d378375c1d0461ba790d3376f34e019d095d/sdk/src/main/java/com/iamport/sdk/data/sdk/IamPortRequest.kt#L22)
어떤 부분에서 문제가 되시는지요?

**Comment by hanbit-valla** [comment]
0.0.5버전 쓰고있는데요
val pg: String,
    val pay_method: PayMethod = PayMethod.card, // 명세상 필수인지 불명확함, default card
    val escrow: Boolean? = null, // default false
    val merchant_uid: String, // default "random"
    val name: String? = null,

customer_uid가 안보이는데 링크걸어주신거랑 많이 다르네요

**Comment by hanbit-valla** [comment]
0.0.6이 그저께 릴리즈됐네요. 이거엔 들어있습니다
