### ISSUE TITLE
webview mode 관련 질문

### ISSUE THREAD

**Issue by YKW93** [iamport/iamport-android#38]
안녕하세요 

웹뷰모드 사용 시 결제 화면이 조금 늦게 등장해서 progress bar를 보여주려고 하는데
웹뷰 client 설정이 내부에 되어 있어(webViewClient = viewModel.getWebViewClient()) onPageFinished 콜백을 설정 할 수가 없는 거 같은데 이때 밑에 방식으로 loading bus를 observe 하는 방법으로 해결하면 될까요??
~~~
WebViewLiveDataEventBus.loading.observe(this, EventObserver {
            Log.d("test08", "gone 처리")
})
~~~

감사합니다.

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다.

MobileWeb Mode 의 경우 IamPortMobileModeWebViewClient 를 상속하여 webViewClient를 사용할 수 있으나,

WebView Mode 의 경우 webViewClient 를 대치하기 때문에, 현재로는 말씀 주신 것처럼 사용하셔야 할 것 같습니다.

추후 다른 override 함수도 필요한 상황이 있다면 WebView Mode 에서도 상속해서 사용하는 방향을 고려해야 할 것 같습니다.

리포트에 감사드립니다!

**Comment by kjh5833** [comment]
추가 기능 구현 없이 대응 가능한 부분 이므로 닫도록 하겠습니다.
