### ISSUE TITLE
MobileWeb Mode시 webview의 chrome client가 변경되는 점

### ISSUE THREAD

**Issue by extJo** [iamport/iamport-android#39]
안녕하세요 MobileWeb Mode시에 `IamPortMobileWebMode`내부 구현 상, webview의 chrome client의 존재 유무를 무시하고  IamportWebChromeClient를 내부적으로 주입하던데, 
- chrome client를 외부에서 주입 또는
- 작성하신 webview client 로칙처럼 webview의 chrome client 를 사용

둘 중 하나로 변경 가능할까요?

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다.

IamPortMobileModeWebViewClient class 를 상속하여 구현하시고 webview.webViewClient 에 세팅하시면 됩니다
참고
https://github.com/iamport/iamport-android/blob/main/app/src/main/java/com/iamport/sampleapp/MyWebViewClient.kt
https://github.com/iamport/iamport-android/blob/main/app/src/main/java/com/iamport/sampleapp/ui/MobileWebViewModeFragment.kt#L45


해당 내용은 Optional 구현사항 : WebView Mode 와 MobileWeb Mode -> 펼쳐보기 -> 2. MobileWeb Mode -> Custom WebViewClient 의 사용 에 작성되어 있으니 참고 바랍니다.
https://github.com/iamport/iamport-android#optional-%EA%B5%AC%ED%98%84%EC%82%AC%ED%95%AD--webview-mode-%EC%99%80-mobileweb-mode

감사합니다.

**Comment by extJo** [comment]
@kjh5833 
네 이미 구현은 IamPortMobileModeWebViewClient 로 상속하여 구현중입니다.

저희가 내부적으로 custom web chrome client를 사용중이라
아래 
https://github.com/iamport/iamport-android/blob/ef0dfc7c096fa614fc6d2a94dfcea6c0e441b3bd/sdk/src/main/java/com/iamport/sdk/presentation/activity/IamPortMobileWebMode.kt#L67
에서 볼 수 있듯이, 아임포트 측에서 web chrome client를 내부적으로 주입 하는걸로 보입니다.
그래서 저희가 커스텀으로 사용하는 web chrome client가 동작하지 않아서 이슈로 남겨드렸습니다.

그리고 web chrome client는 webViewClient가 아닌 WebView에서 설정하는것이지 않나요?

**Comment by kjh5833** [comment]
@extJo 
WebChromeClient 말씀이시군요.

말씀하신 것 처럼 custom 대응이 아직 되어 있지 않습니다만,
IamPortMobileModeWebViewClient 과 같이 상속하시어 사용하게끔 수정하면 될 것으로 보입니다.

작업이 완료되면 공지 드리겠습니다.
감사합니다.

**Comment by kjh5833** [comment]
@extJo 안녕하세요. 아임포트 기술지원팀입니다.

1.1.0-dev01 을 릴리즈 하였습니다. 해당 버전으로 이용해보시기 바랍니다.

문제가 없다면 PR merge 하고 정식 배포하겠습니다.

감사합니다.

**Comment by extJo** [comment]
@kjh5833
따로 문제가 되는부분은 없는 것 같습니다.
빠른 피드백 감사합니다
