### ISSUE TITLE
타겟 sdk 버전이 31일 경우, 매니페스트 merge 문제

### ISSUE THREAD

**Issue by levin-yu** [iamport/iamport-android#44]
Manifest merger failed : android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

컴파일& 타겟 sdk가 31일 경우 매니페스트 merge문제가 있습니다.
안드로이드 12부터는 외부에서 액세스 할 수 있는 서비스나 액티비티등에 export를 명시적으로 표기해야 하는데 sdk 매니페스트를 보면 그렇지 않습니다.

안드로이드 12 대응이 필요합니다.

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다.

플러그인 내부에서 사용하는 activity 의 intent-filter 를 사용하지 않아 제거하였습니다.
해당 [커밋](https://github.com/iamport/iamport-android/pull/43/commits/8c6a65a311ca1a85d5bd3cdf1d762e0c07613367) 참조바라며 #43 PR 에 포함되어 다음 hotfix 버전에 배포 예정입니다.

불편 하시겠으나, 배포 이전까진 targetSdkVersion 을 31 미만으로 설정해주시기 바랍니다.

문의 사항이 있다면 연락 주시기 바랍니다.
제보에 감사드립니다!

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다. 

v1.2.0 을 릴리즈 하였습니다.
해당 버전으로 이용해주시기 바랍니다.

문제가 있으시다면 다시 이슈 오픈 부탁 드립니다.

감사합니다.
