### ISSUE TITLE
webviewMode 사용시 질문

### ISSUE THREAD

**Issue by ehog0613** [iamport/iamport-android#61]
안녕하세요 궁금한점이 있어 문의드립니다.
webviewMode 사용시 오른쪽 상단에 x버튼이 떴다가 사라지는데요.
따로 appBar에 X버튼이 존재해서 웹뷰 자체에서 뜨는 x버튼을 안뜨게 하고싶은데요.
혹시 방법이 있을까요?

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다.
`imp_uid` 및 이슈가 발생하는 스크린샷과 재현영상을 첨부주시면 검토하도록 하겠습니다.
감사합니다.

**Comment by ehog0613** [comment]
https://user-images.githubusercontent.com/20302334/175867333-09d10d84-8d4e-4ee0-88fe-14a008e53edb.mp4

로딩시 잠깐 뜨는 오른쪽 상단 x 버튼 입니다

**Comment by kjh5833** [comment]
아임포트 기술지원팀입니다.
해당 부분 아임포트에서 버튼을 생성하는 부분이 아닌,
본인인증 결페이지 자체에서 컨트롤하는 영역이므로, 수정이 어렵습니다.
참고 부탁드립니다. 감사합니다.

**Comment by ehog0613** [comment]
확인했습니다. 좋은 하루 되세요.
