### ISSUE TITLE
WebViewActivity 가로모드

### ISSUE THREAD

**Issue by leesunr-dev** [iamport/iamport-android#62]
```
        <activity
            android:name=".presentation.activity.WebViewActivity"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:screenOrientation="portrait"
            android:configChanges="keyboardHidden|orientation|screenSize|screenLayout|smallestScreenSize"
            android:theme="@style/Theme.AppCompat.Transparent.NoActionBar">
        </activity>
```
안녕하세요.
가로모드를 지원하는 앱에서 아임포트 결제로 넘어갈때 화면이 회전되어 불편함이 있습니다.
화면 회전이 되도록 수정 요청드립니다

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다.
PG 에서 제공하는 결제 화면 UI 들이 세로 기반이기 때문에
가로로 고정시 오히려 UI 깨짐이나 고객의 불편함을 초래할 수 있어 현재 세로모드로 구현되어 있습니다.
또한, 결제를 위해 페이북이나 카드앱으로 이동시에도 세로 UI 가 사용되기 때문에 결제를 세로형태에서 하게 됩니다.
특별한 이유가 없다면 가로모드 지원 계획은 없으며 WebViewActivity 를 쓰지않는
[webview mode](https://github.com/iamport/iamport-android#optional-%EA%B5%AC%ED%98%84%EC%82%AC%ED%95%AD--webview-mode-%EC%99%80-mobileweb-mode) 사용시 원하시는대로 커스텀하게 UI 를 구성하실 수 있으니 참고 부탁드립니다.
감사합니다.

**Comment by leesunr-dev** [comment]
@kjh5833 
빠른답변 감사합니다. 좋은 하루 되세요~

**Comment by kjh5833** [comment]
해당 이슈는 닫도록 하겠습니다.
