### ISSUE TITLE
네이버페이 결제과정중 웹뷰 멈춤증상

### ISSUE THREAD

**Issue by leesunr-dev** [iamport/iamport-android#63]
안녕하세요 담당자님
네이버 페이를 사용하다 몇가지 오류가 있어 문의 드립니다.
해당 증상이 아임포트 웹뷰 구현 과정에서 발생한건지 네이버페이쪽 문제인지 확인이 필요합니다.

**재현과정**
- 네이버페이 결제를 실행합니다.
- 로그인상태 에서 우측 상단 X 아이콘을 클릭합니다.
- 결제 취소 Dialog가 출력됩니다.
- Dialog 바깥영역을 터치합니다.
- WebView 영역 전체가 아무 반응도 하지 않습니다 (스크롤, 클릭등)
- 뒤로가기 물리버튼으로 아임포트 결제를 종료합니다.
- 다시 네이버페이 혹은 다른 타입(이니시스, 카카오페이 등)의 결제를 실행합니다.
- 무한로딩상태로 아무 동작도 하지 않습니다.

**Comment by kjh5833** [comment]
@leesunr-dev 안녕하세요. 아임포트 기술지원팀입니다.

https://user-images.githubusercontent.com/12838090/179653814-07ba4e5c-ecb0-4d0f-896f-42399768c077.mp4

고객님의 가이드대로 확인하려 했으나, 위 첨부 영상과 같이 정상동작 하고 있습니다.
상세한 재현 케이스를 전달 주실 수 있을까요?

감사합니다.

**Comment by leesunr-dev** [comment]
https://user-images.githubusercontent.com/89774934/179665426-4f319765-5a21-4369-b5f3-4afe975d97d2.mov

@kjh5833 
재현과정 영상을 첨부합니다.
X 버튼 클릭후 확인 버튼을 누르지말고 바깥영역을 터치하면 발생합니다.

**Comment by kjh5833** [comment]
@leesunr-dev 아임포트 기술지원팀입니다.
아임포트 상 버그가 맞는 것으로 보입니다.
원인 분석 후에 공유 드리겠습니다.
이슈 리포팅에 감사드립니다.

**Comment by kjh5833** [comment]
@leesunr-dev 안녕하세요. 아임포트 기술지원팀입니다.

버그 수정 반영하여 snapshot 이 release 되었습니다.

```
implementation 'com.github.iamport:iamport-android:fix~js-confirm-bug-SNAPSHOT'
```

차주 내로 정식버저닝하여 배포하도록 하겠습니다.

감사합니다.

**Comment by leesunr-dev** [comment]
@kjh5833 
빠른 대응 감사합니다. 좋은 하루 되세요

**Comment by kjh5833** [comment]
안녕하세요. 아임포트 기술지원팀입니다.
`1.3.5` 가 배포되었습니다.
`implementation 'com.github.iamport:iamport-android:v1.3.5'`
확인 부탁드립니다.
이슈는 닫도록 하겠습니다! 감사합니다.
